kind: Service
apiVersion: v1
metadata:
  name: travelappservice-prod
spec:
  type: LoadBalancer
  selector:
    app: {{ .Values.selectApp }}
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
